env: "NODE_ENV=test"
language: "node_js"
before_script:
  - "npm install -g coffee twerp"
  - "echo $PATH"
  - "which coffee"
  - "./build-apiaxle.sh"
script: "make test"
node_js:
  - "node"
  - "iojs"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
services:
  - redis-server
