env:
  - NODE_ENV=test
  - CXX=g++-4.8
language: "node_js"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  hosts:
    - redis
before_script:
  - "npm install -g coffee-script twerp"
  - "./build-apiaxle.sh"
script: "make test"
node_js:
  - "node"
  - "iojs"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
services:
  - redis-server
